spring:
  data:
    mongodb:
      host: localhost
      port: 21017
      database: todos

server:
  port: 8000

logging:
  file: logs/todo_app.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

